"""empty message

Revision ID: 22cabc437712
Revises: 87a552dfdb18
Create Date: 2024-06-26 07:18:53.126703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22cabc437712'
down_revision = '87a552dfdb18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
