"""empty message

Revision ID: ce9e77a9b081
Revises: 8cad7cb35256
Create Date: 2024-07-24 06:03:14.165561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9e77a9b081'
down_revision = '8cad7cb35256'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invite_code_code', sa.String(length=64), nullable=True))
        batch_op.create_foreign_key('fk_users_invite_code', 'invite_code', ['invite_code_code'], ['code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('invite_code_code')

    # ### end Alembic commands ###
